import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import NavBar from "./components/NavBar";
import { ToastContainer } from "react-toastify";
import  toast,{ Toaster } from "react-hot-toast";
import 'react-toastify/dist/ReactToastify.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <Providers>

        <NavBar />

        {children}

        <Toaster position="top-center" reverseOrder={false} />

        </Providers> 
        </body>
    </html>
  );
}
